language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coverage
  - pip install python-coveralls
# command to run tests
script:
  - nosetests tests.test_basic --verbose --with-coverage --cover-package=ebi.ols
after_success:
  - coveralls
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: BkrSPAkOM5aTOpeyO9vZnHdZ0LF1PLk0r2HtcXN2eTMyiHoGXkl6VUjdAL8EkzI4gunW2GProdSIjHpf60WdiEmKAulMdJRI+xyUbuxnY31mwiikS9HYwqmPBbMTf0Mh2pMBngZRFs+gaFZDUMTfLfp+8MQfU1R54yb6hPuVt5I=