language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coverage
# command to run tests
script:
  - nosetests --with-coverage --cover-erase --cover-package=ebi.ols
notifications:
  email:
    on_success: change
    on_failure: always
  slack: genomes-ebi:ZVN9oaY6GQ7HDSBtmQC5f5PL