language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - nosetests
notifications:
  email:
    on_success: change
    on_failure: always
  slack: genomes-ebi:ZVN9oaY6GQ7HDSBtmQC5f5PL